### ISSUE TITLE
Daemon console not showing

### ISSUE THREAD

**Issue by Gingeropolous** [JamesCullum/Monero-Installer#1]
I unclicked "Hide the Monero Daemon Console" but nothing changed. 

Ah, that only changes startup behavior. So you need to unclick it, and then restart the UI. Is it possible to change this? It should be mentioned that a restart is required to see the daemon console. 

Also, lightwallet didn't load... but it lightwallet generally doesn't work for me at all. ( I don't know why).

Would it be possible to package Shen Noethers MiniNodo web-gui for the wallet? It requires setting up the wallet in RPC mode and running a nodejs instance..... that would be sweet.

This is awesome!!!!! Thanks so much!!!

**Comment by JamesCullum** [comment]
Thanks for giving me your feedback, i really appreciate it!

It does try to show the console when clicking but that smh doesnt work reliably. I will take another look into it and will surely find some solution.

I already asked in the Reddit thread what other wallets are more reliable and are actively managed. I will definitly add another wallet but i dont think a full webserver including NodeJS is a good way to go for a small/lightweight client. The client is supposed to be lightweight and easy while the full node package deals with more technical stuff.
